paths:
  output_dir: /results/length_normalization/mean
training:
  wandb_run_name: len_norm_mean
  wandb_tags:
    - grpo
    - h100
    - modal
    - len_norm

  use_compile: false
  track_peak_memory: false
  use_gradient_checkpointing: false
  use_bnb_adamw8bit: false
  use_vllm_sleep_mode: true
  gradient_accumulation_steps: 64
  old_log_probs_train_size: 4
  loss_type: reinforce_with_baseline
  n_grpo_steps: 200
  learning_rate: 3e-5
  checkpoint_interval: 8
  normalize_mode: mean
vllm:
  gpu_memory_utilization: 0.2