paths:
  output_dir: /results/lr_sweep/lr_3e-6
training:
  wandb_run_name: lr_sweep_3e-6
  wandb_tags:
    - grpo
    - h100
    - modal
    - lr_sweep

  use_compile: false
  track_peak_memory: false
  use_gradient_checkpointing: false
  use_bnb_adamw8bit: false
  use_vllm_sleep_mode: true
  gradient_accumulation_steps: 64
  old_log_probs_train_size: 4
  loss_type: reinforce_with_baseline
  n_grpo_steps: 100
  learning_rate: 3e-6
  checkpoint_interval: 8
vllm:
  gpu_memory_utilization: 0.2
