paths:
  output_dir: /home/aayush/RESULTS/GRPO/test_h100_modal
training:
  wandb_run_name: test_h100_modal
  wandb_tags:
    - grpo
    - h100
    - modal
    - test

  use_compile: false # compile does not seem to work well with MODAL H100
  track_peak_memory: false
  use_gradient_checkpointing: false  
  use_bnb_adamw8bit: false      
  use_vllm_sleep_mode: true     
  gradient_accumulation_steps: 64
  old_log_probs_train_size: 4
  loss_type: reinforce_with_baseline
  n_grpo_steps: 20
vllm:
  gpu_memory_utilization: 0.2